/**
 * Mock Data for Home Screen Development
 * This will be replaced with real API data in the future
 */

import { Meal, ScheduledMeal, WeeklyMealPlan } from "@/types/nutrition";
import { Exercise, ScheduledExercise, WeeklyWorkoutPlan } from "@/types/workout";
import { DailyProgress, Streak } from "@/types/progress";
import { GroceryItem } from "@/types/grocery";

// Mock Meals
export const MOCK_MEALS: Meal[] = [
  {
    id: "1",
    name: "Breakfast",
    calories: 320,
    macros: {
      carbs: 45,
      protein: 12,
      fat: 8,
    },
  },
  {
    id: "2",
    name: "Morning Snack",
    calories: 95,
    macros: {
      carbs: 15,
      protein: 3,
      fat: 2,
    },
  },
  {
    id: "3",
    name: "Lunch",
    calories: 465,
    macros: {
      carbs: 52,
      protein: 28,
      fat: 15,
    },
  },
  {
    id: "4",
    name: "Afternoon Snack",
    calories: 140,
    macros: {
      carbs: 20,
      protein: 5,
      fat: 6,
    },
  },
  {
    id: "5",
    name: "Dinner",
    calories: 460,
    macros: {
      carbs: 38,
      protein: 32,
      fat: 18,
    },
  },
];

// Mock Exercises
export const MOCK_EXERCISES: Exercise[] = [
  {
    id: "1",
    name: "Bench Press",
    sets: 4,
    reps: 8,
    rir: 2,
    restTime: 120,
    muscleGroup: "Chest",
  },
  {
    id: "2",
    name: "Military Press",
    sets: 3,
    reps: 10,
    rir: 2,
    restTime: 90,
    muscleGroup: "Shoulders",
  },
  {
    id: "3",
    name: "Tricep Extensions",
    sets: 3,
    reps: 12,
    rir: 1,
    restTime: 60,
    muscleGroup: "Triceps",
  },
  {
    id: "4",
    name: "Bicep Curls",
    sets: 3,
    reps: 12,
    rir: 2,
    restTime: 60,
    muscleGroup: "Biceps",
  },
];

// Mock Daily Progress
export const MOCK_PROGRESS: DailyProgress = {
  date: new Date().toISOString(),
  caloriesConsumed: 1480,
  caloriesTarget: 2100,
  steps: 8432,
  stepsTarget: 10000,
  weightChange: -0.2, // kg lost
  exercisesCompleted: 3,
  exercisesTotal: 4,
  completionPercentage: 85,
};

// Mock Streak
export const MOCK_STREAK: Streak = {
  currentStreak: 5,
  longestStreak: 12,
  lastActiveDate: new Date().toISOString(),
};

// Mock Scheduled Meals for Meal Plan Calendar
export const MOCK_SCHEDULED_MEALS: ScheduledMeal[] = [
  // Sunday, Nov 10, 2025
  {
    id: "m1-1",
    name: "Oatmeal with Berries",
    calories: 320,
    macros: { carbs: 45, protein: 12, fat: 8 },
    date: "2025-11-10",
    time: "08:00",
    type: "breakfast",
  },
  {
    id: "m1-2",
    name: "Greek Yogurt & Nuts",
    calories: 180,
    macros: { carbs: 12, protein: 15, fat: 8 },
    date: "2025-11-10",
    time: "10:30",
    type: "morning_snack",
  },
  {
    id: "m1-3",
    name: "Grilled Chicken Salad",
    calories: 450,
    macros: { carbs: 15, protein: 35, fat: 28 },
    date: "2025-11-10",
    time: "13:00",
    type: "lunch",
  },
  {
    id: "m1-4",
    name: "Apple with Almond Butter",
    calories: 200,
    macros: { carbs: 25, protein: 5, fat: 12 },
    date: "2025-11-10",
    time: "16:00",
    type: "afternoon_snack",
  },
  {
    id: "m1-5",
    name: "Salmon with Quinoa",
    calories: 520,
    macros: { carbs: 35, protein: 40, fat: 22 },
    date: "2025-11-10",
    time: "19:00",
    type: "dinner",
  },

  // Monday, Nov 11, 2025
  {
    id: "m2-1",
    name: "Scrambled Eggs & Toast",
    calories: 380,
    macros: { carbs: 35, protein: 20, fat: 18 },
    date: "2025-11-11",
    time: "08:00",
    type: "breakfast",
  },
  {
    id: "m2-2",
    name: "Protein Smoothie",
    calories: 280,
    macros: { carbs: 30, protein: 25, fat: 8 },
    date: "2025-11-11",
    time: "10:30",
    type: "morning_snack",
  },
  {
    id: "m2-3",
    name: "Turkey & Avocado Wrap",
    calories: 480,
    macros: { carbs: 40, protein: 32, fat: 20 },
    date: "2025-11-11",
    time: "13:00",
    type: "lunch",
  },
  {
    id: "m2-4",
    name: "Hummus & Veggies",
    calories: 180,
    macros: { carbs: 18, protein: 6, fat: 10 },
    date: "2025-11-11",
    time: "16:00",
    type: "afternoon_snack",
  },
  {
    id: "m2-5",
    name: "Steak with Sweet Potato",
    calories: 580,
    macros: { carbs: 45, protein: 42, fat: 24 },
    date: "2025-11-11",
    time: "19:00",
    type: "dinner",
  },

  // Tuesday, Nov 12, 2025
  {
    id: "m3-1",
    name: "Protein Pancakes",
    calories: 350,
    macros: { carbs: 42, protein: 28, fat: 10 },
    date: "2025-11-12",
    time: "08:00",
    type: "breakfast",
  },
  {
    id: "m3-2",
    name: "Cottage Cheese & Fruit",
    calories: 220,
    macros: { carbs: 28, protein: 18, fat: 4 },
    date: "2025-11-12",
    time: "10:30",
    type: "morning_snack",
  },
  {
    id: "m3-3",
    name: "Chicken Rice Bowl",
    calories: 520,
    macros: { carbs: 55, protein: 38, fat: 16 },
    date: "2025-11-12",
    time: "13:00",
    type: "lunch",
  },
  {
    id: "m3-4",
    name: "Protein Bar",
    calories: 250,
    macros: { carbs: 30, protein: 20, fat: 8 },
    date: "2025-11-12",
    time: "16:00",
    type: "afternoon_snack",
  },
  {
    id: "m3-5",
    name: "Baked Cod with Vegetables",
    calories: 420,
    macros: { carbs: 25, protein: 45, fat: 12 },
    date: "2025-11-12",
    time: "19:00",
    type: "dinner",
  },

  // Wednesday, Nov 13, 2025
  {
    id: "m4-1",
    name: "Oatmeal with Berries",
    calories: 320,
    macros: { carbs: 45, protein: 12, fat: 8 },
    date: "2025-11-13",
    time: "08:00",
    type: "breakfast",
  },
  {
    id: "m4-2",
    name: "Greek Yogurt & Nuts",
    calories: 180,
    macros: { carbs: 12, protein: 15, fat: 8 },
    date: "2025-11-13",
    time: "10:30",
    type: "morning_snack",
  },
  {
    id: "m4-3",
    name: "Tuna Salad",
    calories: 380,
    macros: { carbs: 12, protein: 35, fat: 20 },
    date: "2025-11-13",
    time: "13:00",
    type: "lunch",
  },
  {
    id: "m4-4",
    name: "Apple with Almond Butter",
    calories: 200,
    macros: { carbs: 25, protein: 5, fat: 12 },
    date: "2025-11-13",
    time: "16:00",
    type: "afternoon_snack",
  },
  {
    id: "m4-5",
    name: "Chicken Stir Fry",
    calories: 480,
    macros: { carbs: 38, protein: 42, fat: 18 },
    date: "2025-11-13",
    time: "19:00",
    type: "dinner",
  },

  // Thursday, Nov 14, 2025
  {
    id: "m5-1",
    name: "Breakfast Burrito",
    calories: 450,
    macros: { carbs: 48, protein: 25, fat: 18 },
    date: "2025-11-14",
    time: "08:00",
    type: "breakfast",
  },
  {
    id: "m5-2",
    name: "Protein Smoothie",
    calories: 280,
    macros: { carbs: 30, protein: 25, fat: 8 },
    date: "2025-11-14",
    time: "10:30",
    type: "morning_snack",
  },
  {
    id: "m5-3",
    name: "Grilled Chicken Salad",
    calories: 450,
    macros: { carbs: 15, protein: 35, fat: 28 },
    date: "2025-11-14",
    time: "13:00",
    type: "lunch",
  },
  {
    id: "m5-4",
    name: "Hummus & Veggies",
    calories: 180,
    macros: { carbs: 18, protein: 6, fat: 10 },
    date: "2025-11-14",
    time: "16:00",
    type: "afternoon_snack",
  },
  {
    id: "m5-5",
    name: "Salmon with Quinoa",
    calories: 520,
    macros: { carbs: 35, protein: 40, fat: 22 },
    date: "2025-11-14",
    time: "19:00",
    type: "dinner",
  },

  // Friday, Nov 15, 2025
  {
    id: "m6-1",
    name: "French Toast",
    calories: 420,
    macros: { carbs: 52, protein: 15, fat: 16 },
    date: "2025-11-15",
    time: "08:00",
    type: "breakfast",
  },
  {
    id: "m6-2",
    name: "Cottage Cheese & Fruit",
    calories: 220,
    macros: { carbs: 28, protein: 18, fat: 4 },
    date: "2025-11-15",
    time: "10:30",
    type: "morning_snack",
  },
  {
    id: "m6-3",
    name: "Turkey & Avocado Wrap",
    calories: 480,
    macros: { carbs: 40, protein: 32, fat: 20 },
    date: "2025-11-15",
    time: "13:00",
    type: "lunch",
  },
  {
    id: "m6-4",
    name: "Protein Bar",
    calories: 250,
    macros: { carbs: 30, protein: 20, fat: 8 },
    date: "2025-11-15",
    time: "16:00",
    type: "afternoon_snack",
  },
  {
    id: "m6-5",
    name: "Caesar Salad with Chicken",
    calories: 480,
    macros: { carbs: 20, protein: 38, fat: 28 },
    date: "2025-11-15",
    time: "19:00",
    type: "dinner",
  },

  // Saturday, Nov 16, 2025
  {
    id: "m7-1",
    name: "Scrambled Eggs & Toast",
    calories: 380,
    macros: { carbs: 35, protein: 20, fat: 18 },
    date: "2025-11-16",
    time: "08:00",
    type: "breakfast",
  },
  {
    id: "m7-2",
    name: "Greek Yogurt & Nuts",
    calories: 180,
    macros: { carbs: 12, protein: 15, fat: 8 },
    date: "2025-11-16",
    time: "10:30",
    type: "morning_snack",
  },
  {
    id: "m7-3",
    name: "Chicken Rice Bowl",
    calories: 520,
    macros: { carbs: 55, protein: 38, fat: 16 },
    date: "2025-11-16",
    time: "13:00",
    type: "lunch",
  },
  {
    id: "m7-4",
    name: "Apple with Almond Butter",
    calories: 200,
    macros: { carbs: 25, protein: 5, fat: 12 },
    date: "2025-11-16",
    time: "16:00",
    type: "afternoon_snack",
  },
  {
    id: "m7-5",
    name: "Beef Tacos",
    calories: 550,
    macros: { carbs: 42, protein: 35, fat: 26 },
    date: "2025-11-16",
    time: "19:00",
    type: "dinner",
  },
];

// Mock Weekly Meal Plan
export const MOCK_WEEKLY_MEAL_PLAN: WeeklyMealPlan = {
  weekStart: "2025-11-10", // Sunday
  meals: MOCK_SCHEDULED_MEALS,
};

// Mock Scheduled Exercises for Workout Plan Calendar
export const MOCK_SCHEDULED_EXERCISES: ScheduledExercise[] = [
  // Sunday, Nov 10, 2025 - Upper Body Day
  {
    id: "e1-1",
    name: "Arm Circles",
    sets: 2,
    reps: 15,
    rir: 5,
    restTime: 30,
    date: "2025-11-10",
    time: "08:00",
    type: "warm-up",
  },
  {
    id: "e1-2",
    name: "Band Pull-Aparts",
    sets: 2,
    reps: 20,
    rir: 5,
    restTime: 30,
    date: "2025-11-10",
    time: "08:05",
    type: "warm-up",
  },
  {
    id: "e1-3",
    name: "Bench Press",
    sets: 4,
    reps: 8,
    rir: 2,
    restTime: 120,
    muscleGroup: "Chest",
    date: "2025-11-10",
    time: "08:15",
    type: "main",
  },
  {
    id: "e1-4",
    name: "Incline Dumbbell Press",
    sets: 4,
    reps: 10,
    rir: 2,
    restTime: 90,
    muscleGroup: "Chest",
    date: "2025-11-10",
    time: "08:35",
    type: "main",
  },
  {
    id: "e1-5",
    name: "Cable Flyes",
    sets: 3,
    reps: 12,
    rir: 1,
    restTime: 60,
    muscleGroup: "Chest",
    date: "2025-11-10",
    time: "08:55",
    type: "main",
  },
  {
    id: "e1-6",
    name: "Overhead Press",
    sets: 4,
    reps: 8,
    rir: 2,
    restTime: 90,
    muscleGroup: "Shoulders",
    date: "2025-11-10",
    time: "09:10",
    type: "main",
  },
  {
    id: "e1-7",
    name: "Lateral Raises",
    sets: 3,
    reps: 15,
    rir: 1,
    restTime: 60,
    muscleGroup: "Shoulders",
    date: "2025-11-10",
    time: "09:30",
    type: "main",
  },
  {
    id: "e1-8",
    name: "Tricep Dips",
    sets: 3,
    reps: 12,
    rir: 2,
    restTime: 60,
    muscleGroup: "Triceps",
    date: "2025-11-10",
    time: "09:45",
    type: "main",
  },
  {
    id: "e1-9",
    name: "Chest Stretch",
    sets: 2,
    reps: 1,
    rir: 0,
    restTime: 30,
    date: "2025-11-10",
    time: "10:00",
    type: "stretch",
  },
  {
    id: "e1-10",
    name: "Shoulder Stretch",
    sets: 2,
    reps: 1,
    rir: 0,
    restTime: 30,
    date: "2025-11-10",
    time: "10:05",
    type: "stretch",
  },

  // Monday, Nov 11, 2025 - Lower Body Day
  {
    id: "e2-1",
    name: "Leg Swings",
    sets: 2,
    reps: 15,
    rir: 5,
    restTime: 30,
    date: "2025-11-11",
    time: "08:00",
    type: "warm-up",
  },
  {
    id: "e2-2",
    name: "Hip Circles",
    sets: 2,
    reps: 20,
    rir: 5,
    restTime: 30,
    date: "2025-11-11",
    time: "08:05",
    type: "warm-up",
  },
  {
    id: "e2-3",
    name: "Back Squats",
    sets: 4,
    reps: 8,
    rir: 2,
    restTime: 180,
    muscleGroup: "Legs",
    date: "2025-11-11",
    time: "08:15",
    type: "main",
  },
  {
    id: "e2-4",
    name: "Romanian Deadlifts",
    sets: 4,
    reps: 10,
    rir: 2,
    restTime: 120,
    muscleGroup: "Hamstrings",
    date: "2025-11-11",
    time: "08:40",
    type: "main",
  },
  {
    id: "e2-5",
    name: "Bulgarian Split Squats",
    sets: 3,
    reps: 12,
    rir: 2,
    restTime: 90,
    muscleGroup: "Legs",
    date: "2025-11-11",
    time: "09:05",
    type: "main",
  },
  {
    id: "e2-6",
    name: "Leg Press",
    sets: 4,
    reps: 12,
    rir: 2,
    restTime: 90,
    muscleGroup: "Legs",
    date: "2025-11-11",
    time: "09:25",
    type: "main",
  },
  {
    id: "e2-7",
    name: "Leg Curls",
    sets: 3,
    reps: 15,
    rir: 1,
    restTime: 60,
    muscleGroup: "Hamstrings",
    date: "2025-11-11",
    time: "09:45",
    type: "main",
  },
  {
    id: "e2-8",
    name: "Calf Raises",
    sets: 4,
    reps: 20,
    rir: 1,
    restTime: 45,
    muscleGroup: "Calves",
    date: "2025-11-11",
    time: "10:00",
    type: "main",
  },
  {
    id: "e2-9",
    name: "Quad Stretch",
    sets: 2,
    reps: 1,
    rir: 0,
    restTime: 30,
    date: "2025-11-11",
    time: "10:15",
    type: "stretch",
  },
  {
    id: "e2-10",
    name: "Hamstring Stretch",
    sets: 2,
    reps: 1,
    rir: 0,
    restTime: 30,
    date: "2025-11-11",
    time: "10:20",
    type: "stretch",
  },

  // Tuesday, Nov 12, 2025 - Pull Day
  {
    id: "e3-1",
    name: "Scapular Pull-Ups",
    sets: 2,
    reps: 10,
    rir: 5,
    restTime: 30,
    date: "2025-11-12",
    time: "08:00",
    type: "warm-up",
  },
  {
    id: "e3-2",
    name: "Dead Hangs",
    sets: 2,
    reps: 1,
    rir: 5,
    restTime: 30,
    date: "2025-11-12",
    time: "08:05",
    type: "warm-up",
  },
  {
    id: "e3-3",
    name: "Deadlifts",
    sets: 4,
    reps: 6,
    rir: 2,
    restTime: 180,
    muscleGroup: "Back",
    date: "2025-11-12",
    time: "08:15",
    type: "main",
  },
  {
    id: "e3-4",
    name: "Pull-Ups",
    sets: 4,
    reps: 8,
    rir: 2,
    restTime: 120,
    muscleGroup: "Back",
    date: "2025-11-12",
    time: "08:40",
    type: "main",
  },
  {
    id: "e3-5",
    name: "Barbell Rows",
    sets: 4,
    reps: 10,
    rir: 2,
    restTime: 90,
    muscleGroup: "Back",
    date: "2025-11-12",
    time: "09:00",
    type: "main",
  },
  {
    id: "e3-6",
    name: "Face Pulls",
    sets: 3,
    reps: 15,
    rir: 1,
    restTime: 60,
    muscleGroup: "Back",
    date: "2025-11-12",
    time: "09:20",
    type: "main",
  },
  {
    id: "e3-7",
    name: "Bicep Curls",
    sets: 3,
    reps: 12,
    rir: 2,
    restTime: 60,
    muscleGroup: "Biceps",
    date: "2025-11-12",
    time: "09:35",
    type: "main",
  },
  {
    id: "e3-8",
    name: "Hammer Curls",
    sets: 3,
    reps: 12,
    rir: 2,
    restTime: 60,
    muscleGroup: "Biceps",
    date: "2025-11-12",
    time: "09:50",
    type: "main",
  },
  {
    id: "e3-9",
    name: "Back Stretch",
    sets: 2,
    reps: 1,
    rir: 0,
    restTime: 30,
    date: "2025-11-12",
    time: "10:05",
    type: "stretch",
  },
  {
    id: "e3-10",
    name: "Bicep Stretch",
    sets: 2,
    reps: 1,
    rir: 0,
    restTime: 30,
    date: "2025-11-12",
    time: "10:10",
    type: "stretch",
  },

  // Wednesday, Nov 13, 2025 - Upper Body Day
  {
    id: "e4-1",
    name: "Arm Circles",
    sets: 2,
    reps: 15,
    rir: 5,
    restTime: 30,
    date: "2025-11-13",
    time: "08:00",
    type: "warm-up",
  },
  {
    id: "e4-2",
    name: "Band Pull-Aparts",
    sets: 2,
    reps: 20,
    rir: 5,
    restTime: 30,
    date: "2025-11-13",
    time: "08:05",
    type: "warm-up",
  },
  {
    id: "e4-3",
    name: "Dumbbell Press",
    sets: 4,
    reps: 10,
    rir: 2,
    restTime: 90,
    muscleGroup: "Chest",
    date: "2025-11-13",
    time: "08:15",
    type: "main",
  },
  {
    id: "e4-4",
    name: "Cable Crossovers",
    sets: 3,
    reps: 15,
    rir: 1,
    restTime: 60,
    muscleGroup: "Chest",
    date: "2025-11-13",
    time: "08:35",
    type: "main",
  },
  {
    id: "e4-5",
    name: "Arnold Press",
    sets: 4,
    reps: 10,
    rir: 2,
    restTime: 90,
    muscleGroup: "Shoulders",
    date: "2025-11-13",
    time: "08:50",
    type: "main",
  },
  {
    id: "e4-6",
    name: "Front Raises",
    sets: 3,
    reps: 12,
    rir: 1,
    restTime: 60,
    muscleGroup: "Shoulders",
    date: "2025-11-13",
    time: "09:10",
    type: "main",
  },
  {
    id: "e4-7",
    name: "Skull Crushers",
    sets: 3,
    reps: 12,
    rir: 2,
    restTime: 60,
    muscleGroup: "Triceps",
    date: "2025-11-13",
    time: "09:25",
    type: "main",
  },
  {
    id: "e4-8",
    name: "Cable Pushdowns",
    sets: 3,
    reps: 15,
    rir: 1,
    restTime: 60,
    muscleGroup: "Triceps",
    date: "2025-11-13",
    time: "09:40",
    type: "main",
  },
  {
    id: "e4-9",
    name: "Chest Stretch",
    sets: 2,
    reps: 1,
    rir: 0,
    restTime: 30,
    date: "2025-11-13",
    time: "09:55",
    type: "stretch",
  },
  {
    id: "e4-10",
    name: "Tricep Stretch",
    sets: 2,
    reps: 1,
    rir: 0,
    restTime: 30,
    date: "2025-11-13",
    time: "10:00",
    type: "stretch",
  },

  // Thursday, Nov 14, 2025 - Lower Body Day
  {
    id: "e5-1",
    name: "Leg Swings",
    sets: 2,
    reps: 15,
    rir: 5,
    restTime: 30,
    date: "2025-11-14",
    time: "08:00",
    type: "warm-up",
  },
  {
    id: "e5-2",
    name: "Bodyweight Squats",
    sets: 2,
    reps: 20,
    rir: 5,
    restTime: 30,
    date: "2025-11-14",
    time: "08:05",
    type: "warm-up",
  },
  {
    id: "e5-3",
    name: "Front Squats",
    sets: 4,
    reps: 8,
    rir: 2,
    restTime: 150,
    muscleGroup: "Legs",
    date: "2025-11-14",
    time: "08:15",
    type: "main",
  },
  {
    id: "e5-4",
    name: "Walking Lunges",
    sets: 4,
    reps: 12,
    rir: 2,
    restTime: 90,
    muscleGroup: "Legs",
    date: "2025-11-14",
    time: "08:40",
    type: "main",
  },
  {
    id: "e5-5",
    name: "Leg Extensions",
    sets: 3,
    reps: 15,
    rir: 1,
    restTime: 60,
    muscleGroup: "Quads",
    date: "2025-11-14",
    time: "09:00",
    type: "main",
  },
  {
    id: "e5-6",
    name: "Seated Leg Curls",
    sets: 4,
    reps: 12,
    rir: 2,
    restTime: 60,
    muscleGroup: "Hamstrings",
    date: "2025-11-14",
    time: "09:15",
    type: "main",
  },
  {
    id: "e5-7",
    name: "Hip Thrusts",
    sets: 4,
    reps: 12,
    rir: 2,
    restTime: 90,
    muscleGroup: "Glutes",
    date: "2025-11-14",
    time: "09:30",
    type: "main",
  },
  {
    id: "e5-8",
    name: "Standing Calf Raises",
    sets: 4,
    reps: 20,
    rir: 1,
    restTime: 45,
    muscleGroup: "Calves",
    date: "2025-11-14",
    time: "09:50",
    type: "main",
  },
  {
    id: "e5-9",
    name: "Hip Flexor Stretch",
    sets: 2,
    reps: 1,
    rir: 0,
    restTime: 30,
    date: "2025-11-14",
    time: "10:05",
    type: "stretch",
  },
  {
    id: "e5-10",
    name: "Glute Stretch",
    sets: 2,
    reps: 1,
    rir: 0,
    restTime: 30,
    date: "2025-11-14",
    time: "10:10",
    type: "stretch",
  },

  // Friday, Nov 15, 2025 - Full Body Day
  {
    id: "e6-1",
    name: "Jumping Jacks",
    sets: 2,
    reps: 20,
    rir: 5,
    restTime: 30,
    date: "2025-11-15",
    time: "08:00",
    type: "warm-up",
  },
  {
    id: "e6-2",
    name: "High Knees",
    sets: 2,
    reps: 30,
    rir: 5,
    restTime: 30,
    date: "2025-11-15",
    time: "08:05",
    type: "warm-up",
  },
  {
    id: "e6-3",
    name: "Power Cleans",
    sets: 4,
    reps: 6,
    rir: 2,
    restTime: 150,
    muscleGroup: "Full Body",
    date: "2025-11-15",
    time: "08:15",
    type: "main",
  },
  {
    id: "e6-4",
    name: "Push Press",
    sets: 4,
    reps: 8,
    rir: 2,
    restTime: 120,
    muscleGroup: "Shoulders",
    date: "2025-11-15",
    time: "08:40",
    type: "main",
  },
  {
    id: "e6-5",
    name: "T-Bar Rows",
    sets: 4,
    reps: 10,
    rir: 2,
    restTime: 90,
    muscleGroup: "Back",
    date: "2025-11-15",
    time: "09:00",
    type: "main",
  },
  {
    id: "e6-6",
    name: "Goblet Squats",
    sets: 3,
    reps: 15,
    rir: 2,
    restTime: 60,
    muscleGroup: "Legs",
    date: "2025-11-15",
    time: "09:20",
    type: "main",
  },
  {
    id: "e6-7",
    name: "Dumbbell Lunges",
    sets: 3,
    reps: 12,
    rir: 2,
    restTime: 60,
    muscleGroup: "Legs",
    date: "2025-11-15",
    time: "09:35",
    type: "main",
  },
  {
    id: "e6-8",
    name: "Plank",
    sets: 3,
    reps: 1,
    rir: 1,
    restTime: 60,
    muscleGroup: "Core",
    date: "2025-11-15",
    time: "09:50",
    type: "main",
  },
  {
    id: "e6-9",
    name: "Full Body Stretch",
    sets: 2,
    reps: 1,
    rir: 0,
    restTime: 30,
    date: "2025-11-15",
    time: "10:05",
    type: "stretch",
  },
  {
    id: "e6-10",
    name: "Deep Breathing",
    sets: 2,
    reps: 10,
    rir: 0,
    restTime: 30,
    date: "2025-11-15",
    time: "10:10",
    type: "stretch",
  },

  // Saturday, Nov 16, 2025 - Upper Body Day
  {
    id: "e7-1",
    name: "Resistance Band Rows",
    sets: 2,
    reps: 15,
    rir: 5,
    restTime: 30,
    date: "2025-11-16",
    time: "08:00",
    type: "warm-up",
  },
  {
    id: "e7-2",
    name: "Push-Up Plus",
    sets: 2,
    reps: 10,
    rir: 5,
    restTime: 30,
    date: "2025-11-16",
    time: "08:05",
    type: "warm-up",
  },
  {
    id: "e7-3",
    name: "Incline Barbell Press",
    sets: 4,
    reps: 8,
    rir: 2,
    restTime: 120,
    muscleGroup: "Chest",
    date: "2025-11-16",
    time: "08:15",
    type: "main",
  },
  {
    id: "e7-4",
    name: "Dumbbell Flyes",
    sets: 3,
    reps: 12,
    rir: 1,
    restTime: 60,
    muscleGroup: "Chest",
    date: "2025-11-16",
    time: "08:35",
    type: "main",
  },
  {
    id: "e7-5",
    name: "Seated Dumbbell Press",
    sets: 4,
    reps: 10,
    rir: 2,
    restTime: 90,
    muscleGroup: "Shoulders",
    date: "2025-11-16",
    time: "08:50",
    type: "main",
  },
  {
    id: "e7-6",
    name: "Reverse Flyes",
    sets: 3,
    reps: 15,
    rir: 1,
    restTime: 60,
    muscleGroup: "Shoulders",
    date: "2025-11-16",
    time: "09:10",
    type: "main",
  },
  {
    id: "e7-7",
    name: "Close-Grip Bench",
    sets: 3,
    reps: 10,
    rir: 2,
    restTime: 90,
    muscleGroup: "Triceps",
    date: "2025-11-16",
    time: "09:25",
    type: "main",
  },
  {
    id: "e7-8",
    name: "Overhead Extensions",
    sets: 3,
    reps: 12,
    rir: 1,
    restTime: 60,
    muscleGroup: "Triceps",
    date: "2025-11-16",
    time: "09:40",
    type: "main",
  },
  {
    id: "e7-9",
    name: "Shoulder Stretch",
    sets: 2,
    reps: 1,
    rir: 0,
    restTime: 30,
    date: "2025-11-16",
    time: "09:55",
    type: "stretch",
  },
  {
    id: "e7-10",
    name: "Tricep Stretch",
    sets: 2,
    reps: 1,
    rir: 0,
    restTime: 30,
    date: "2025-11-16",
    time: "10:00",
    type: "stretch",
  },
];

// Mock Weekly Workout Plan
export const MOCK_WEEKLY_WORKOUT_PLAN: WeeklyWorkoutPlan = {
  weekStart: "2025-11-10", // Sunday
  exercises: MOCK_SCHEDULED_EXERCISES,
};

/**
 * Mock Grocery Items
 * Consolidated shopping list from all meals in the monthly plan
 * Includes variety of categories, purchase frequencies, and storage types
 */
export const MOCK_GROCERY_ITEMS: GroceryItem[] = [
  // VEGETABLES (mostly weekly, fresh)
  {
    id: "g1",
    ingredientId: "ing1",
    name: "Spinach",
    quantity: 200,
    unit: "g",
    category: "vegetables",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m1-3", "m2-3"],
  },
  {
    id: "g2",
    ingredientId: "ing2",
    name: "Tomatoes",
    quantity: 3,
    unit: "pieces",
    category: "vegetables",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: true,
    isCustom: false,
    mealSources: ["m1-3", "m4-3"],
  },
  {
    id: "g3",
    ingredientId: "ing3",
    name: "Bell peppers",
    quantity: 2,
    unit: "pieces",
    category: "vegetables",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m2-5", "m4-5"],
  },
  {
    id: "g4",
    ingredientId: "ing4",
    name: "Broccoli",
    quantity: 300,
    unit: "g",
    category: "vegetables",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m3-5"],
  },
  {
    id: "g5",
    ingredientId: "ing5",
    name: "Carrots",
    quantity: 500,
    unit: "g",
    category: "vegetables",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m2-4", "m5-4"],
  },
  {
    id: "g6",
    ingredientId: "ing6",
    name: "Lettuce",
    quantity: 1,
    unit: "pieces",
    category: "vegetables",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m1-3", "m5-3", "m6-5"],
  },
  {
    id: "g7",
    ingredientId: "ing7",
    name: "Avocado",
    quantity: 4,
    unit: "pieces",
    category: "vegetables",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m2-3", "m6-3"],
  },
  {
    id: "g8",
    ingredientId: "ing8",
    name: "Sweet Potato",
    quantity: 800,
    unit: "g",
    category: "vegetables",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m2-5"],
  },

  // PROTEINS (mix of weekly fresh and frozen)
  {
    id: "g9",
    ingredientId: "ing9",
    name: "Chicken breast",
    quantity: 500,
    unit: "g",
    category: "proteins",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m1-3", "m3-3", "m4-5", "m5-3", "m6-5"],
  },
  {
    id: "g10",
    ingredientId: "ing10",
    name: "Salmon fillet",
    quantity: 300,
    unit: "g",
    category: "proteins",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m1-5", "m5-5"],
  },
  {
    id: "g11",
    ingredientId: "ing11",
    name: "Eggs",
    quantity: 12,
    unit: "pieces",
    category: "proteins",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: true,
    isCustom: false,
    mealSources: ["m2-1", "m7-1"],
  },
  {
    id: "g12",
    ingredientId: "ing12",
    name: "Turkey breast",
    quantity: 300,
    unit: "g",
    category: "proteins",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m2-3", "m6-3"],
  },
  {
    id: "g13",
    ingredientId: "ing13",
    name: "Beef steak",
    quantity: 400,
    unit: "g",
    category: "proteins",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m2-5", "m7-5"],
  },
  {
    id: "g14",
    ingredientId: "ing14",
    name: "Cod fillet",
    quantity: 250,
    unit: "g",
    category: "proteins",
    purchaseFrequency: "weekly",
    storageType: "frozen",
    isChecked: false,
    isCustom: false,
    mealSources: ["m3-5"],
  },
  {
    id: "g15",
    ingredientId: "ing15",
    name: "Tuna",
    quantity: 200,
    unit: "g",
    category: "proteins",
    purchaseFrequency: "monthly",
    storageType: "pantry",
    isChecked: false,
    isCustom: false,
    mealSources: ["m4-3"],
  },

  // GRAINS (mostly monthly, pantry)
  {
    id: "g16",
    ingredientId: "ing16",
    name: "Brown rice",
    quantity: 1,
    unit: "kg",
    category: "grains",
    purchaseFrequency: "monthly",
    storageType: "pantry",
    isChecked: false,
    isCustom: false,
    mealSources: ["m3-3", "m7-3"],
  },
  {
    id: "g17",
    ingredientId: "ing17",
    name: "Quinoa",
    quantity: 500,
    unit: "g",
    category: "grains",
    purchaseFrequency: "monthly",
    storageType: "pantry",
    isChecked: false,
    isCustom: false,
    mealSources: ["m1-5", "m5-5"],
  },
  {
    id: "g18",
    ingredientId: "ing18",
    name: "Oats",
    quantity: 1,
    unit: "kg",
    category: "grains",
    purchaseFrequency: "monthly",
    storageType: "pantry",
    isChecked: false,
    isCustom: false,
    mealSources: ["m1-1", "m4-1"],
  },
  {
    id: "g19",
    ingredientId: "ing19",
    name: "Whole wheat bread",
    quantity: 1,
    unit: "pieces",
    category: "grains",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m2-1", "m7-1"],
  },
  {
    id: "g20",
    ingredientId: "ing20",
    name: "Whole wheat tortillas",
    quantity: 8,
    unit: "pieces",
    category: "grains",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m2-3", "m5-1", "m6-3", "m7-5"],
  },

  // DAIRY (weekly, fresh)
  {
    id: "g21",
    ingredientId: "ing21",
    name: "Greek yogurt",
    quantity: 500,
    unit: "g",
    category: "dairy",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m1-2", "m4-2", "m7-2"],
  },
  {
    id: "g22",
    ingredientId: "ing22",
    name: "Cottage cheese",
    quantity: 400,
    unit: "g",
    category: "dairy",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m3-2", "m6-2"],
  },
  {
    id: "g23",
    ingredientId: "ing23",
    name: "Milk",
    quantity: 2,
    unit: "l",
    category: "dairy",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m2-2", "m3-1", "m5-2"],
  },
  {
    id: "g24",
    ingredientId: "ing24",
    name: "Cheese",
    quantity: 200,
    unit: "g",
    category: "dairy",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m5-1", "m6-5"],
  },

  // FRUITS (weekly, fresh)
  {
    id: "g25",
    ingredientId: "ing25",
    name: "Berries",
    quantity: 300,
    unit: "g",
    category: "fruits",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m1-1", "m4-1"],
  },
  {
    id: "g26",
    ingredientId: "ing26",
    name: "Bananas",
    quantity: 6,
    unit: "pieces",
    category: "fruits",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m2-2", "m5-2"],
  },
  {
    id: "g27",
    ingredientId: "ing27",
    name: "Apples",
    quantity: 4,
    unit: "pieces",
    category: "fruits",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m1-4", "m4-4", "m7-4"],
  },
  {
    id: "g28",
    ingredientId: "ing28",
    name: "Mixed fruit",
    quantity: 400,
    unit: "g",
    category: "fruits",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m3-2", "m6-2"],
  },

  // OILS & CONDIMENTS (monthly, pantry)
  {
    id: "g29",
    ingredientId: "ing29",
    name: "Olive oil",
    quantity: 500,
    unit: "ml",
    category: "oils",
    purchaseFrequency: "monthly",
    storageType: "pantry",
    isChecked: false,
    isCustom: false,
    mealSources: [],
  },
  {
    id: "g30",
    ingredientId: "ing30",
    name: "Almond butter",
    quantity: 350,
    unit: "g",
    category: "condiments",
    purchaseFrequency: "monthly",
    storageType: "pantry",
    isChecked: false,
    isCustom: false,
    mealSources: ["m1-4", "m4-4", "m7-4"],
  },
  {
    id: "g31",
    ingredientId: "ing31",
    name: "Hummus",
    quantity: 400,
    unit: "g",
    category: "condiments",
    purchaseFrequency: "weekly",
    storageType: "fresh",
    isChecked: false,
    isCustom: false,
    mealSources: ["m2-4", "m5-4"],
  },

  // SPICES & OTHERS (monthly, pantry)
  {
    id: "g32",
    ingredientId: "ing32",
    name: "Mixed nuts",
    quantity: 300,
    unit: "g",
    category: "other",
    purchaseFrequency: "monthly",
    storageType: "pantry",
    isChecked: false,
    isCustom: false,
    mealSources: ["m1-2", "m4-2", "m7-2"],
  },
  {
    id: "g33",
    ingredientId: "ing33",
    name: "Protein powder",
    quantity: 1,
    unit: "kg",
    category: "other",
    purchaseFrequency: "monthly",
    storageType: "pantry",
    isChecked: false,
    isCustom: false,
    mealSources: ["m2-2", "m5-2"],
  },
  {
    id: "g34",
    ingredientId: "ing34",
    name: "Protein bars",
    quantity: 10,
    unit: "pieces",
    category: "other",
    purchaseFrequency: "monthly",
    storageType: "pantry",
    isChecked: false,
    isCustom: false,
    mealSources: ["m3-4", "m6-4"],
  },
];
